# Generated by Django 2.2.4 on 2019-10-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoption',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30, null=True)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Dont wish to disclose')])),
                ('pet_age', models.IntegerField()),
                ('pet_color', models.CharField(blank=True, max_length=50, null=True)),
                ('pet_count', models.IntegerField(default=1)),
                ('pet_images', models.ImageField(blank=True, null=True, upload_to='pet_images')),
                ('pet_bio', models.TextField(max_length=500)),
                ('pet_point_of_contact', models.CharField(max_length=500)),
                ('pet_email_id', models.EmailField(max_length=254)),
                ('pet_adoption_location', models.CharField(max_length=500)),
                ('pet_location_longitude', models.CharField(max_length=500)),
                ('pet_location_latitude', models.CharField(max_length=500)),
                ('pet_adoption_status', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', max_length=10)),
                ('pet_adoption_centre_logo', models.ImageField(blank=True, null=True, upload_to='adoption_centre_logo')),
                ('vendor_timestamp', models.DateTimeField(auto_now_add=True)),
                ('vendor_update', models.DateTimeField(auto_now=True)),
                ('pet_vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
            options={
                'db_table': 'adoption',
            },
        ),
        migrations.CreateModel(
            name='adoption_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.IntegerField(choices=[(1, 'Shortlisted'), (2, 'Rejected'), (3, 'Pending')], default=3)),
                ('preferred_day', models.IntegerField(choices=[(1, 'Weekday'), (2, 'Weekend')], default=1)),
                ('preferred_time', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=2)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.adoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_login_details')),
            ],
            options={
                'db_table': 'adoption_relation',
            },
        ),
    ]
