# Generated by Django 2.2.4 on 2019-10-14 19:31

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_contact_number', phone_field.models.PhoneField(blank=True, help_text='Contact number', max_length=31)),
                ('user_existing_pet_details', models.IntegerField(choices=[(1, 'Yes, I have had pets in the past'), (2, 'No, I have no relation to them'), (3, 'I donot remember'), (4, 'I am not sure if i could be counted as a pet to my parents')])),
                ('user_home_size', models.IntegerField(choices=[(1, '1 BHK'), (2, '<2 BHK'), (3, 'Villa'), (4, 'Cubical'), (5, 'Mini home')])),
                ('user_flatmates', models.IntegerField(choices=[(1, 'Friends'), (2, 'Family'), (3, 'Friends and Family'), (4, 'Friends who could turn into family'), (5, 'I do not like living with anyone')])),
                ('user_job_timings', models.IntegerField(choices=[(1, '9AM- 5PM( Regular government job)'), (2, 'IT employee'), (3, 'Startup employee(Not sure if i go home regularly)'), (4, 'Freelancer(I am the king)'), (5, 'I donot need to work because I am still a student/king of my empire')])),
                ('user_income', models.IntegerField(choices=[(1, '5000-25000(Before EMIs)'), (2, '20000-80000(Before EMIs)'), (3, 'No steady income'), (4, 'I am rich'), (5, 'Write your own answer')])),
                ('user_godfather_details', models.TextField()),
                ('user_parenting_style', models.IntegerField(choices=[(1, 'Tough parent'), (2, 'Soft parent'), (3, ' I am not sure parent'), (4, 'Moderate parent')])),
                ('user_adoption_counselling', models.IntegerField(choices=[(1, 'No, I am an expert'), (2, 'Yes, that will be lovely'), (3, 'Not sure about my time yet')])),
                ('user_medical_history', models.IntegerField(choices=[(1, 'Yes'), (2, 'NO'), (3, 'Never'), (4, 'Not Sure')])),
                ('user_callback', models.IntegerField(choices=[(1, 'Yes'), (2, 'Definitely a yes'), (3, 'Does not look like I have an option so YES')])),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='user_login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_token', models.CharField(max_length=1000)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_profile_pic', models.TextField(blank=True, null=True)),
                ('user_email_id', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user_login_details',
            },
        ),
    ]
