# Generated by Django 2.2.4 on 2019-12-04 20:05

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_questionnaire_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owner')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('W', 'Dont wish to disclose')], max_length=1)),
                ('bio', models.TextField(max_length=500)),
                ('dob', models.DateField(max_length=8)),
                ('longitude', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('home_address', models.CharField(max_length=500)),
                ('emergency_address', models.CharField(max_length=500)),
                ('emergency_contact', phone_field.models.PhoneField(blank=True, help_text='Emergency Contact number', max_length=31)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('no_of_pets', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user_login_details')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30, null=True)),
                ('pet_birthday', models.DateField(max_length=8)),
                ('pet_type', models.CharField(max_length=30)),
                ('pet_breed', models.CharField(max_length=30)),
                ('pet_gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('pet_age', models.IntegerField()),
                ('pet_images', models.ImageField(blank=True, null=True, upload_to='pet')),
                ('pet_bio', models.TextField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.owner')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
    ]
