# Generated by Django 2.2.4 on 2019-12-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_owner_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pet1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet1_matched', to='users.pet')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_pet2', to='users.pet')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_matched', to='users.user_login_details')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='with_user2', to='users.user_login_details')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('Y', 'Like'), ('N', 'Dislike')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pet1_likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet1', to='users.pet')),
                ('pet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet2', to='users.pet')),
                ('user1_likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_likes', to='users.user_login_details')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='users.user_login_details')),
            ],
            options={
                'db_table': 'like',
            },
        ),
    ]
